name = "dml-ab-test-private"
client_id = "${SHOPIFY_API_KEY}"
application_url = "${SHOPIFY_APP_URL}"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""
include_config_on_deploy = true

[access_scopes]
scopes = "read_orders,read_themes,write_script_tags"

[auth]
redirect_urls = [
  "${SHOPIFY_APP_URL}/auth/callback",
  "${SHOPIFY_APP_URL}/auth/shopify/callback",
  "${SHOPIFY_APP_URL}/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "orders/create" ]
  uri = "/webhooks/orders_create"

[pos]
embedded = false
