name = "DML AB Test"
client_id = "b9ad9c8312703f0e31de61fa82b00b72"
application_url = "https://dml-ab-test.vercel.app"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = ""

[access_scopes]
scopes = "read_themes"

[auth]
redirect_urls = [
  "https://dml-ab-test.vercel.app/auth/callback",
  "https://dml-ab-test.vercel.app/auth/shopify/callback",
  "https://dml-ab-test.vercel.app/api/auth/callback"
]

[webhooks]
api_version = "2025-01"

[pos]
embedded = false
