ALTER TABLE "Shop"
  ADD COLUMN IF NOT EXISTS "defaultTrafficSplit"   INTEGER NOT NULL DEFAULT 50,
  ADD COLUMN IF NOT EXISTS "defaultAssignmentMode" TEXT    NOT NULL DEFAULT 'STICKY',
  ADD COLUMN IF NOT EXISTS "certaintyThreshold"    INTEGER NOT NULL DEFAULT 85;
